server:
  port: 9090

spring:
  application:
    name: password-validator

springdoc:
  api-docs:
    path=/api-docs: /api-docs

#prometeus
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
